### ISSUE TITLE
Feature suggestion: Removing leaves

### ISSUE THREAD

**Issue by SlimeDog** [Dudenn/TreeGravity#2]
1. Calculate the footprint of the logs that will be dropped.
1. Calculate a cube that encompasses the footprint, from ground to the height of the taller trees (20?).
1. Drop the logs as now.
1. Remove the leaves in the cube; even better (configurable), apply gravity to them. Of course, leaves should not be dropped as items, unless they are cut by shears.

**Comment by Dudenn** [comment]
Adding this to the community suggestions on the spigot forum, thanks for the idea! I think this would be a great addition to the plugin.

**Comment by SlimeDog** [comment]
Any chance this will be included in the "VERY needed" update?
