### ISSUE TITLE
the calculation of woods and saplings is wrong when the tree is very huge

### ISSUE THREAD

**Issue by QianNangong** [Dudenn/TreeGravity#4]
When I try to cut down such a huge tree.
![ef118b1d98e5b2adb46180ddfe8bfb9a](https://user-images.githubusercontent.com/4312700/49335675-191b9780-f62d-11e8-9cea-eaf248809828.jpg)
The server will be hang and then crash.
And then I try to restart the server and log in, it shows that TG generate above 6,000 item drops.
![84e3d33fc6125f5c57070cdb510e2544](https://user-images.githubusercontent.com/4312700/49335695-87605a00-f62d-11e8-97fb-4288fe103c00.jpg)
I think the result is wrong, there would be some bugs inside the algorithm.

**Comment by Dudenn** [comment]
I will look into this once I add epic world generator support. Only tested the plugin with slightly more extreme conditions than vanilla MC, large trees with at the most 300 logs on them. Closing the issue for now since EWG and TreeGravity aren't compatible at this time, no idea why they aren't..
